services:
  db:
    image: mysql:8.0.34
    user: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: firstdb
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
