"""add table

Revision ID: c4d1a95a079c
Revises: 
Create Date: 2024-04-08 20:24:12.596332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d1a95a079c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False, comment='トピック'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.Column('ignored_at', sa.TIMESTAMP(), nullable=True, comment='無効日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False, comment='ステップ'),
    sa.Column('code', sa.Text(), nullable=True, comment='コード'),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.Column('ignored_at', sa.TIMESTAMP(), nullable=True, comment='無効日時'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_steps')
    op.drop_table('topic')
    # ### end Alembic commands ###
